title: Ryan's GitHub Training Page
author: rchillard-gov
email: something.something@sba.gov
description: > # this means to ignore newlines until "baseurl:"
 A short treatise on my love of sugar, coding, and all things in between

# social links
twitter_username: twitter-is-for-the-birds
github_username:  rchillard-gov

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
